name: hello world

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  HelloWorldJob:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: "Hello World Step"
        run: echo "Hello World!"
        shell: bash

  GoodByeJob:
    runs-on: ubuntu-latest
    steps:
      - name: "GoodBye World Step"
        run: echo "GoodBye World!"
        shell: bash
